apiVersion: v1
kind: secret
metadata:
  name: backend-secret
type: Opaque
stringData:
# Replace this with a secure random value in real environments.
  DJANGO_SECRET_KEY: "change-me-to-a-secure-random-key-in-production"  